import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link';
import Login from './login';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex justify-around items-center bg-slate-400 h-20 text-lg font-semibold  '>
        <Link href='/diaryform'>일기쓰기</Link>
        {/* <Login/> */}
        <Link href='/'>목록</Link>
        </div>
        {children}</body>
    </html>
  )
}
